// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/app/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/app/repository.go -destination=internal/mocks/appmock/repository.go -package=appmock
//

// Package appmock is a generated GoMock package.
package appmock

import (
	context "context"
	reflect "reflect"

	app "github.com/ryoeuyo/sso-microservice/internal/domain/app"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ByID mocks base method.
func (m *MockRepository) ByID(ctx context.Context, id int32) (app.App, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByID", ctx, id)
	ret0, _ := ret[0].(app.App)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByID indicates an expected call of ByID.
func (mr *MockRepositoryMockRecorder) ByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByID", reflect.TypeOf((*MockRepository)(nil).ByID), ctx, id)
}
