// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/token/issuer.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/token/issuer.go -destination=internal/mocks/tokenmock/issuer.go -package=tokenmock
//

// Package tokenmock is a generated GoMock package.
package tokenmock

import (
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	token "github.com/ryoeuyo/sso-microservice/internal/domain/token"
	gomock "go.uber.org/mock/gomock"
)

// MockIssuer is a mock of Issuer interface.
type MockIssuer struct {
	ctrl     *gomock.Controller
	recorder *MockIssuerMockRecorder
	isgomock struct{}
}

// MockIssuerMockRecorder is the mock recorder for MockIssuer.
type MockIssuerMockRecorder struct {
	mock *MockIssuer
}

// NewMockIssuer creates a new mock instance.
func NewMockIssuer(ctrl *gomock.Controller) *MockIssuer {
	mock := &MockIssuer{ctrl: ctrl}
	mock.recorder = &MockIssuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIssuer) EXPECT() *MockIssuerMockRecorder {
	return m.recorder
}

// HashRefresh mocks base method.
func (m *MockIssuer) HashRefresh(plain string) []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashRefresh", plain)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// HashRefresh indicates an expected call of HashRefresh.
func (mr *MockIssuerMockRecorder) HashRefresh(plain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashRefresh", reflect.TypeOf((*MockIssuer)(nil).HashRefresh), plain)
}

// IssueAccess mocks base method.
func (m *MockIssuer) IssueAccess(userID uuid.UUID, appID int32, roles []string, secret string) (string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueAccess", userID, appID, roles, secret)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// IssueAccess indicates an expected call of IssueAccess.
func (mr *MockIssuerMockRecorder) IssueAccess(userID, appID, roles, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueAccess", reflect.TypeOf((*MockIssuer)(nil).IssueAccess), userID, appID, roles, secret)
}

// IssueRefresh mocks base method.
func (m *MockIssuer) IssueRefresh(userID uuid.UUID, appID int32) (token.RefreshToken, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueRefresh", userID, appID)
	ret0, _ := ret[0].(token.RefreshToken)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// IssueRefresh indicates an expected call of IssueRefresh.
func (mr *MockIssuerMockRecorder) IssueRefresh(userID, appID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueRefresh", reflect.TypeOf((*MockIssuer)(nil).IssueRefresh), userID, appID)
}

// ParseAccess mocks base method.
func (m *MockIssuer) ParseAccess(signed, secret string) (token.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseAccess", signed, secret)
	ret0, _ := ret[0].(token.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseAccess indicates an expected call of ParseAccess.
func (mr *MockIssuerMockRecorder) ParseAccess(signed, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseAccess", reflect.TypeOf((*MockIssuer)(nil).ParseAccess), signed, secret)
}

// ParseAccessUnverified mocks base method.
func (m *MockIssuer) ParseAccessUnverified(signed string) (token.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseAccessUnverified", signed)
	ret0, _ := ret[0].(token.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseAccessUnverified indicates an expected call of ParseAccessUnverified.
func (mr *MockIssuerMockRecorder) ParseAccessUnverified(signed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseAccessUnverified", reflect.TypeOf((*MockIssuer)(nil).ParseAccessUnverified), signed)
}
